import { useState } from "react";
import * as Tabs from "@radix-ui/react-tabs";
import { City } from "./CityMap.jsx";
import { Badge, Button, Empty, Icon, Locations, Meter, Metric, Requirements } from "./components.jsx";

const SECTIONS = [["city", "City", "city"], ["contacts", "Contacts", "people"], ["herd", "Herd", "blood"], ["resources", "Resources", "brief"], ["errand", "Errand", "arrow"], ["power", "Your power", "crown"]];
const money = value => `$${Math.round(Number(value) || 0).toLocaleString("en-US")}`;
const districtName = (model, id) => model.districts.find(d => d.id === id)?.name || id;

function Contacts({ model, command }) {
  const [selected, setSelected] = useState(model.contacts[0]?.id);
  const person = model.contacts.find(p => p.id === selected) || model.contacts[0];
  return <div className="vb-dossier"><div className="vb-contact-list" aria-label="Contacts">{model.contacts.map((p, i) => <button type="button" key={p.id} aria-pressed={p.id === person?.id} onClick={() => setSelected(p.id)}><span className="vb-contact-monogram" aria-hidden="true">{String(i + 1).padStart(2, "0")}</span><span><strong>{p.name}</strong><small>{p.met ? p.suspended ? "Agreement suspended" : "In your network" : p.available ? "Ready to meet" : "Introduction needed"}</small></span><span aria-hidden="true">↗</span></button>)}</div>
    {person && <article className="vb-person-detail"><span className="vb-eyebrow">{person.role}</span><h2>{person.name}</h2><p className="vb-lead">{person.greeting}</p><Badge tone={person.suspended ? "danger" : person.met ? "good" : "neutral"}>{person.status}</Badge><div className="vb-statline"><Metric label="Trust" value={person.trust}/><Metric label="Debt" value={money(person.debt)}/><Metric label="Jobs completed" value={person.jobs}/></div><h3>What this connection opens</h3><p>{person.benefits}</p>{!person.available && <><h3>Earn the introduction</h3><Requirements items={person.requirements}/></>}{person.suspended && <p className="vb-warning">{person.reason || "The agreement must be repaired through work or compensation."}</p>}<h3>Find them</h3><p>{districtName(model, person.destination?.districtId || person.districtId)} · Services are negotiated in person.</p><Locations command={command} target={`contact:${person.id}`}/></article>}
  </div>;
}
function Herd({ model, command }) {
  return <section className="vb-section"><div className="vb-section-intro"><div><span className="vb-eyebrow">BLOOD WITHOUT THE HUNT</span><h2>Your herd</h2><p>Consent is personal. A hunting permit does not make someone a donor.</p></div><div className="vb-statline"><Metric label="Ready now" value={model.herd.filter(p => p.ready).length}/><Metric label="Permitted" value={model.herd.filter(p => p.permitted).length}/></div></div>
    <div className="vb-editorial-grid">{model.herd.map(person => <article key={person.id} className="vb-editorial-card"><span className="vb-eyebrow">{districtName(model, person.districtId)}</span><h3>{person.name}</h3><Badge tone={person.ready ? "good" : person.refused || person.dead ? "danger" : "neutral"}>{person.status}</Badge><dl className="vb-facts"><div><dt>Patron</dt><dd>{person.patron}</dd></div><div><dt>Consent</dt><dd>{person.permitted ? "Agreement active" : "Not authorised"}</dd></div><div><dt>Donation</dt><dd>−{person.relief} hunger</dd></div></dl><p>{person.reason || "Meet in person and request a donation. Recovery takes four minutes of active play."}</p><Locations command={command} target={`donor:${person.id}`} disabled={person.dead}/>{!person.permitted && !person.dead && <Button onClick={() => command("locate", { target: `contact:${person.contactId}` })}>Find the patron</Button>}</article>)}</div></section>;
}
function Resources({ model, command }) {
  return <section className="vb-section"><div className="vb-section-intro"><div><span className="vb-eyebrow">SUPPLY & OWNERSHIP</span><h2>Make the city work for you.</h2><p>Staff produce every 90 seconds of active play. Stored blood must be collected on site.</p></div></div><div className="vb-statline"><Metric label="Cash" value={money(model.cash)}/><Metric label="Income / cycle" value={money(model.income)}/><Metric label="Debt" value={money(model.debt)}/><Metric label="Blood carried" value={`${model.bags}/4`}/></div><div className="vb-actions"><Button icon="blood" disabled={!model.bags || model.hunger <= 0} onClick={() => command("blood")}>Use blood · return to play</Button><Button disabled={model.vitality >= 100} onClick={() => command("mend")}>Mend · +30 vitality / +12 hunger</Button></div>
    <div className="vb-editorial-grid">{model.assets.map(asset => <article key={asset.id} className="vb-editorial-card"><span className="vb-eyebrow">{districtName(model, asset.districtId)}</span><h3>{asset.name}</h3><Badge tone={asset.suspended ? "danger" : asset.level ? "good" : "neutral"}>{asset.suspended ? "Suspended" : ["Not owned", "Investor", "Controlled"][asset.level]}</Badge><p>{asset.description}</p><div className="vb-statline"><Metric label="Income" value={money(asset.income)}/><Metric label="Blood / cycle" value={asset.production}/><Metric label="Stored bags" value={`${asset.reserve}/12`}/></div><p>Operator: <strong>{asset.operator}</strong> · {asset.policy} policy</p><p className="vb-next-requirement">{asset.requirement}</p><Locations command={command} target={`asset:${asset.id}`}/></article>)}</div></section>;
}
function Errand({ model, command, confirmation }) {
  const errand = model.errand;
  if (!errand) return <Empty title="No outstanding errand" action={<Button primary onClick={() => command("tab", { tab: "contacts" })}>Find a contact</Button>}>Work earns cash, trust and introductions. You can carry one errand at a time.</Empty>;
  return <section className="vb-section vb-errand"><span className="vb-eyebrow">CURRENT ERRAND · {errand.issuer}</span><h2>{errand.current.title}</h2><p className="vb-lead">{errand.current.description}</p><div className="vb-errand-steps">{errand.steps.map((step, i) => <article key={step.target} data-state={step.state}><span className="vb-step-number">{step.state === "done" ? "✓" : `0${i + 1}`}</span><div><small>{step.state === "current" ? "DO THIS NOW" : step.state === "done" ? "COMPLETED" : "THEN"}</small><h3>{step.title}</h3><p>{step.description}</p></div></article>)}</div><Badge>{errand.cargo}</Badge><div className="vb-statline"><Metric label="Total reward" value={money(errand.reward)}/><Metric label="Debt repaid" value={money(errand.repaid)}/><Metric label="Cash received" value={money(errand.cash)}/><Metric label="Trust" value={`+${errand.trust}`}/></div><Locations command={command} target="delivery"/>
    <div className="vb-abandon">{confirmation ? <div role="alert"><h3>Abandon this errand?</h3><p>You will forfeit this cargo and reward. This cannot be undone.</p><div className="vb-actions"><Button danger onClick={() => command("confirm-abandon")}>Abandon errand</Button><Button primary onClick={() => command("cancel-confirm")}>Keep working</Button></div></div> : <Button danger onClick={() => command("abandon")}>Abandon errand…</Button>}</div></section>;
}
function Power({ model, command }) {
  const completed = model.requirements.filter(r => r.met).length;
  return <section className="vb-section vb-power"><span className="vb-eyebrow">FROM SURVIVAL TO SOVEREIGNTY</span><h2>{model.stage}</h2><p className="vb-lead">Power is a network of people who need you.</p><div className="vb-power-path">{["Survivor", "Connected", "Investor", "Power broker", "Prince of the city"].map(stage => <span key={stage} data-current={model.stage === stage}>{stage}</span>)}</div><div className="vb-power-grid"><article><h3>Your next move</h3><p className="vb-lead">{model.next.text}</p><p>{model.next.why}</p><Locations command={command} target={model.next.target}/></article><article><h3>The city compact</h3><p>{completed} of {model.requirements.length} requirements met</p><Meter value={completed} max={model.requirements.length || 1} label="City compact requirements"/><Requirements items={model.requirements}/><Button onClick={() => command("locate", { target: "contact:sire" })}>Locate the Sire</Button></article></div><h3>Recent agreements</h3><div className="vb-history">{model.notices.map((n, i) => <p key={i}>{n.text}</p>)}</div></section>;
}
export function Domain({ snapshot, geometry, command }) {
  const model = snapshot.domain;
  if (!model) return <Empty title="Your network is not ready">The campaign has not supplied a domain snapshot.</Empty>;
  return <Tabs.Root className="vb-domain" value={snapshot.tab} onValueChange={tab => command("tab", { tab })} orientation="horizontal">
    <div className="vb-domain-rail"><Tabs.List className="vb-domain-nav" aria-label="Your domain">{SECTIONS.map(([id, name, icon], i) => <Tabs.Trigger className="vb-domain-tab" key={id} value={id}><Icon name={icon}/><span>{name}</span><kbd>{i + 1}</kbd>{id === "errand" && model.errand && <i aria-label="Active errand"/>}</Tabs.Trigger>)}</Tabs.List><div className="vb-rail-foot"><small>YOUR STANDING</small><strong>{model.stage}</strong><span>World paused</span></div></div>
    <div className="vb-domain-main"><div className="vb-domain-summary"><span>{money(model.cash)} <small>cash</small></span><span>{model.bags}/4 <small>blood</small></span><span>{money(model.income)} <small>income / cycle</small></span><span>{money(model.debt)} <small>debt</small></span></div>{snapshot.feedback && <p className="vb-feedback" role="status">{snapshot.feedback}</p>}
      <Tabs.Content value="city" className="vb-tab-panel"><City model={model} geometry={geometry} selection={snapshot.selection} command={command}/></Tabs.Content>
      <Tabs.Content value="contacts" className="vb-tab-panel scroll"><Contacts model={model} command={command}/></Tabs.Content>
      <Tabs.Content value="herd" className="vb-tab-panel scroll"><Herd model={model} command={command}/></Tabs.Content>
      <Tabs.Content value="resources" className="vb-tab-panel scroll"><Resources model={model} command={command}/></Tabs.Content>
      <Tabs.Content value="errand" className="vb-tab-panel scroll"><Errand model={model} command={command} confirmation={snapshot.confirmation}/></Tabs.Content>
      <Tabs.Content value="power" className="vb-tab-panel scroll"><Power model={model} command={command}/></Tabs.Content>
    </div>
  </Tabs.Root>;
}
